[package]
name = "ninfra"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
shiplift = "0.7.0"
warp = "0.3.5"
sqlite = "0.30.5"
